### ISSUE TITLE
Possible typo and error on a2 word2vec/Word2Vec.ipynb

### ISSUE THREAD

**Issue by wanburana** [chaklam-silpasuwanchai/Natural-Language-Processing#1]
1. The first term should be
`-u_o (1 - sigmoid(u_o.T v_c))` or `u_o (sigmoid(u_o.T v_c) - 1)`
instead of  
`u_o (1 - sigmoid(u_o.T v_c))`

(i'm not very confident, but replacing that allow me to pass the test function)

![image](https://user-images.githubusercontent.com/66191669/151660457-72925089-f091-4ff1-bc38-192675ba7f95.png)

2. `{U}` on line 35 and 59 on `test_word2vec()` function cause an error KeyError: "U"  (since `{U}` is intepreted as variable when using .format() )
replacing `{U}` with `{{U}}` fix the problem for me

![image](https://user-images.githubusercontent.com/66191669/151661083-b9191a6a-d3ac-4f6a-887d-48b408908f04.png)

**Comment by chaklam-silpasuwanchai** [comment]
Thanks!

Yes, that was a typo!   There should be a minus sign in front.

As for the {U}, that's strange.  Let me look at other students and see if they also have the same problems before I look more deeply into the issue.
